src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $release_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $runtime;

    /**
     * @ORM\Column(type="integer")
     */
    private $moviedb_id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="hasSeen")
     */
    private $hasSeen;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Genres", inversedBy="movies")
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $background;

    /**
     * @ORM\Column(name="created_at", type="datetime", options={"default": "CURRENT_TIMESTAMP"}, nullable=false)
    */
    private $created_at;

    public function __construct()
    {
        $this->hasSeen = new ArrayCollection();
        $this->genre = new ArrayCollection();
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(?\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


    public function getRuntime(): ?int
    {
        return $this->runtime;
    }

    public function setRuntime(?int $runtime): self
    {
        $this->runtime = $runtime;

        return $this;
    }

    public function getMoviedbId(): ?int
    {
        return $this->moviedb_id;
    }

    public function setMoviedbId(int $moviedb_id): self
    {
        $this->moviedb_id = $moviedb_id;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getHasSeen(): Collection
    {
        return $this->hasSeen;
    }

    public function addHasSeen(User $hasSeen): self
    {
        if (!$this->hasSeen->contains($hasSeen)) {
            $this->hasSeen[] = $hasSeen;
            $hasSeen->addHasSeen($this);
        }

        return $this;
    }

    public function removeHasSeen(User $hasSeen): self
    {
        if ($this->hasSeen->contains($hasSeen)) {
            $this->hasSeen->removeElement($hasSeen);
            $hasSeen->removeHasSeen($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genres[]
     */
    public function getGenre(): Collection
    {
        return $this->genre;
    }

    public function addGenre(Genres $genre): self
    {
        if (!$this->genre->contains($genre)) {
            $this->genre[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genres $genre): self
    {
        if ($this->genre->contains($genre)) {
            $this->genre->removeElement($genre);
        }

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = "https://image.tmdb.org/t/p/original" . $poster;

        return $this;
    }

    public function getBackground(): ?string
    {
        return $this->background;
    }

    public function setBackground(?string $background): self
    {
        $this->background = "https://image.tmdb.org/t/p/original" . $background;

        return $this;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Movie;
use App\Entity\User;
use Symfony\Component\Security\Core\Security;

class MovieController extends AbstractController
//TODO: Ajouter une fonction de recherche
//TODO: Ajouter une fonction de tri sur les pages contenant tous les films.
{
    private function getSimIds(int $id) {
        //TODO: Recupere la liste des films similaires
        $reco = array_slice(json_decode(file_get_contents("https://api.themoviedb.org/3/movie/".$id."/recommendations?api_key=7d43208d19a4ad654a8afdf455744183&language=fr-FR&page=1"), true)["results"],0, 2);
        foreach ($reco as $movie) {
            $results[] = $movie["id"];
        }
        return isset($results) ? $results : [];
    }

    /**
     * @Route("/movie/add/{id}", name="movie_has_seen")
     * @param Security $security
     * @param int $id
     * @return RedirectResponse
     */
    public function addToHasSeen(Security $security, int $id) {
        $user = $security->getUser();
        $movie = $this->getDoctrine()->getRepository(Movie::class)->find($id);

        //TODO: Ajouter un moyen d'ajouter un film vu et un film a voir
        $user->addHasSeen($movie);

        return $this->redirectToRoute("movie", ["id" => $id]);
    }

    /**
     * @Route("/movie/{id}", name="movie")
     * @param $id
     * @return Response
     */
    public function index($id)
    {
        $movie = $this->getDoctrine()->getRepository(Movie::class)->find($id);

        $idList = $this->getSimIds($movie->getMoviedbId());

        //Recuperer les infos des films recommandes par leur id
        $movieList = [];
        foreach ($idList as $i) {
            $movieList[] = $this->getDoctrine()->getRepository(Movie::class)->findOneBy(["moviedb_id" => $i]);
        }
        return $this->render('movie/index.html.twig', [
            'controller_name' => 'MovieController',
            'info' => [
                "id" => $id,
                "background" => $movie->getBackground(),
                "title" => $movie->getTitle(),
                "release_date" => $movie->getReleaseDate(),
                "synopsis" => $movie->getSynopsis()
            ],
            "similar_movies" => array_filter($movieList),
        ]);
    }

    /**
     * @Route("/add/{id}", name="addSeenMovie")
     * @param int $id
     * @param Request $request
     * @return RedirectResponse
     */
    public function addSeen(int $id, Request $request) {
        $movie = $this->getDoctrine()->getRepository(Movie::class)->find($id);
        $user = $this->getUser();
        $user->addHasSeen($movie);
        $em = $this->getDoctrine()->getManager();
        $em->persist($user);
        $em->flush();

        $referer = $request->headers->get("referer");

        return new RedirectResponse($referer, "302");
    }
}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ info.title }}{% endblock %}

{% block body %}

<div id="background-title">
    <div class="" style="background: url('{{ info.background }}'); background-size: cover;">
        {% if info.background != "https://image.tmdb.org/t/p/original" %}<img class="img-fluid" src="{{ info.background }}"/>{% endif %}
    </div>
    <div class="title-block" {% if info.background == "https://image.tmdb.org/t/p/original" %} style="margin-top: 0;" {% endif %}>
        <p class="" style="font-size: 1.5em;">{{ info.title }}</p>
        <p class="text-muted" style="font-size: 1.3em; margin: -10px 0;">{{ info.release_date|date("d M Y") }}</p>
        <p style="font-size:1em; text-align: justify; margin-top: 1em;">
            {% if info.synopsis == "" %}
                Aucun synopsis disponible
            {% else %}
                {{ info.synopsis }}
            {% endif %}
        </p>
    </div>
</div>

{% if app.user %}
    <div id="added-block" class="text-center" style="padding: 10px 0";>
        <a href="{{ path("addSeenMovie", parameters={ id: info.id }) }}" class="myButton">Vu</a>
    </div>
{% else %}
    <div id="added-block">
        <p class="text-center"><a href="{{ path("app_login") }}">Connectez-vous</a> pour ajouter le film</p>
    </div>
{% endif %}

<h1 class="text-center" style="padding-top: 1em; padding-bottom: 1em;">Films Similaires</h1>

<div class="movie-deck">

    {% if similar_movies is empty %}
        <p class="text-center" id="no-similar-movies">Aucun film similaire</p>
    {% else %}
{% for movie in similar_movies %}
{% if movie.poster == "https://image.tmdb.org/t/p/original" %}
<div class="movie-card text-white hover-action" style="background-image: url({{asset('img/placeholder-Movie.png')}}); background-size:100%">
    {% else %}
    <div class="movie-card text-white hover-action" style="background-image: url( {{ movie.poster }}); background-size:cover">
        {% endif %}
        <a href="{{ path("movie", parameters={id: movie.id }) }}">
            <div class="hoverable">
                <div class="hoverable-content">
                    <h5 class="movie-title">{{ movie.title }}</h5>
                    <p class="movie-synopsis">{{ movie.releaseDate|date("d M Y") }}</p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
    {% endif %}
{% endblock %}